class_name BodySlotEnum extends Object
# defining this as class instead enum gives the possibility to extend it
#b.. = bodyparts  (separated for mutation-slots)
const bBase   = 0  #defines overall bodyform
const bFeet   = 1 
const bLegs   = 2
const bTorso  = 3    
const bWings  = 4
const bSkin   = 5  # or fur scales ...
const bPubicHair  = 6 
const bHeadHair   = 7 
const bArms   =   8
const bHands  =   9
const bNeck   =   10
const bFace   =   11 
const bEyes   =   12 
const bEars   =   13 
const bMouth  =   14 
const bTongue =   15
const bTailBase = 16   
const bBreast =   17
const bNipples =  18 
const bPenis =    19 
const bBalls  =   20 
const bVulva  =   21 
const bClit   =   22 
const bWomb   =   23 
const bAnus   =   24 
# slots for wearables
const Feet    =   100 
const Ankles  =   101 
const Legs    =   102 
const Thighs  =   104      #
const Hips    =   104     #belt
const Torso   =   105     #dont use !
const Breast  =   106 
const Nipples =   107 
const Penis =     108 
const Balls  =    109 
const Vulva  =    110 
const Clit    =   111 
const Womb   =    112  #??
const Anus   =    113 
const TailBase   =114 
const TailTip =   115 
const Stomach =   116 
const Chest   =   117 
const Shoulders = 118   
const Wings   =   119 
const Neck    =   120 
const Head    =   121 
const HeadHair=   122 #for Hats
const Face    =   123 #for facemask
const Mouth   =   124 
const Nose    =   125 
const Eyes    =   126 
const Ears    =   127 
const Arms    =   128 
const Wrists  =   129 
const LHand   =   130 
const RHand   =   131 
#U  = under wear    P = piercing 
const uFeet    = 201    #socks stockings
const uAnkles  = 202    #stockings  cuffs
const uLegs    = 203    #stockings
const uThighs  = 204    #garter
const uHips    = 205    #garter  
const uTorso   = 206     #dont use !
const uBreast  = 207    #bra
const pNipples = 208 
#const tStomach = 209 
const uPenis   = 210
const pPenis  =   211 
const uBalls  =   212 
const pBalls  =   213 
const uVulva  =   214 
const pVulva  =   215 
const pClit   =   216 
const uAnus   =   217
const uTailBase=  218
const uTailTip =  219 
const uStomach =  220 
const uChest   =  221    #bra
const uShoulders =222 
const uWings   =  223 
const uNeck    =  224     #necklace
const uHead    =  225     #
const uHeadHair=  226 
const uFace    =  227
const uMouth   =  228 
const pNose    =  229 
const pEyes    =  230 
const pEars    =  231     #earring
const pTongue  =  232 
const pNavel   =  233 
const uArms    =  234 
const uWrists  =  235 
const uLHand   =  236 
const uRHand   =  237
# T = tattoo 
const tStomach = 309 
